lmax_over_nside = 2.5
healpix = true
car = false
output_folder = "output/{tag}"
output_filename_template= "litebird_{tag}_uKCMB_{telescope}-{band}_nside{nside}.fits"
unit = "uK_CMB"
num = 0
output_reference_frame = "G"
instrument_parameters = "../litebirdXS4-private/instrument_model_20230614/litebird_instrument_model.tbl"
